export enum TiposRespuestaEnum {
  ABIERTA = 'ABIERTA',
  OPCION = 'OPCION',
  OPCION_MULTIPLE_SELECCION_SIMPLE = 'OPCION_MULTIPLE_SELECCION_SIMPLE',
  OPCION_MULTIPLE_SELECCION_MULTIPLE = 'OPCION_MULTIPLE_SELECCION_MULTIPLE',
  VERDADERO_FALSO = 'VERDADERO_FALSO'
}
